### ISSUE TITLE
[Suggestions] Custom OpenAI compatible URL

### ISSUE THREAD

**Issue by TheUnawsomeGuy** [Mino260806/KeyboardGPT#1]
Hello, this seems like a novel idea but I use local models that uses openai api format. Could you please implement a way to use custom api urls? Thanks

**Comment by Mino260806** [comment]
Did you see the option to change base url ? (For now it only works with chatgpt)

![ss-1.0.1.jpg](https://github.com/user-attachments/assets/ce17fc44-2321-4761-9885-7f7e0029a219)

**Comment by TheUnawsomeGuy** [comment]
My apologies, I didn't notice the option despite it being in front of me. I however, have another issue. 
![Screenshot_2024-07-27-21-17-34-880_com google android keep](https://github.com/user-attachments/assets/e45db67d-885c-4427-9ff2-ab62823bfb79)

**Comment by Mino260806** [comment]
Seems to be an old chatgpt API

Here's the official one
![image](https://github.com/user-attachments/assets/b913abf6-ca40-4052-9ba4-df144120fd24)

In the one you sent every line starts with "data: "

The problem with ChatGPT is that there's no official java library so I had to code it myself, which removes backward compatibility and makes the API limited. Maybe I'd integrate a python / javascript interpreter in the future and use the official API to avoid this kind of problems.

I coded this as a workaround for you issue, can you see if it solves the problem ? (rename to .apk)
[app-release.zip](https://github.com/user-attachments/files/16400334/app-release.zip)

**Comment by adienox** [comment]
> My apologies, I didn't notice the option despite it being in front of me. I however, have another issue. ![Screenshot_2024-07-27-21-17-34-880_com google android keep](https://private-user-images.githubusercontent.com/7058199/352732342-e45db67d-885c-4427-9ff2-ab62823bfb79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU1NTksIm5iZiI6MTcyMjA5NTI1OSwicGF0aCI6Ii83MDU4MTk5LzM1MjczMjM0Mi1lNDVkYjY3ZC04ODVjLTQ0MjctOWZmMi1hYjYyODIzYmZiNzkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjdUMTU0NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU2NjI1MGQ1NWZiYWU5MWM0ZjQzNGZhMmU3ODMzZjcxMDU4NTI5OTFhMzRlODc0YWI3OWQ5MTk1OTlhMTRmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bde2GdtCDUeJjKIEPy1EgBkHsTCKg-bbatNjiEy0IFs)

I am facing this exact same issue. Even tried the following, still didn't work

> Seems to be an old chatgpt API
> 
> Here's the official one ![image](https://private-user-images.githubusercontent.com/53614199/352740852-b913abf6-ca40-4052-9ba4-df144120fd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU1NTksIm5iZiI6MTcyMjA5NTI1OSwicGF0aCI6Ii81MzYxNDE5OS8zNTI3NDA4NTItYjkxM2FiZjYtY2E0MC00MDUyLTliYTQtZGYxNDQxMjBmZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzQ4NzdjMWU5NzVmMDI1ZmQwMDdhZWMxZjBiZTQwYmViYTFhMTQ1MTY3MjY1NTRkN2NiZGIzODg4YWVmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RAdwyHoV1P47hdn7hPyjypiai8tx1D_IaATlkT3rQQU)
> 
> In the one you sent every line starts with "data: "
> 
> The problem with ChatGPT is that there's no official java library so I had to code it myself, which removes backward compatibility and makes the API limited. Maybe I'd integrate a python / javascript interpreter in the future and use the official API to avoid this kind of problems.
> 
> I coded this as a workaround for you issue, can you see if it solves the problem ? (rename to .apk) [app-release.zip](https://github.com/user-attachments/files/16400334/app-release.zip)

**Comment by Mino260806** [comment]
Working on the issue !

**Comment by Mino260806** [comment]
Fixed with commit e6d80a6f583b62ccf246697a5e47ea0bb7f41837, please update to latest version
