### ISSUE TITLE
Updating keyboard app

### ISSUE THREAD

**Issue by Achyuth072** [Mino260806/KeyboardGPT#11]
How does updating keyboard app work? Do I need repatch newer apk everytime?

**Comment by Mino260806** [comment]
In LSPatch you should select Local (not integrated). And that way, it's enough to update the KeyboardGPT apk without opening LSPatch at all

**Comment by Mino260806** [comment]
In LSPatch you should select Local (not integrated). And that way, it's enough to update the KeyboardGPT apk without opening LSPatch at all

**Comment by Achyuth072** [comment]
> In LSPatch you should patch with Local (not Integrated). And that way, it's enough to update the KeyboardGPT apk without opening LSPatch at all

I'm talking about the keyboard app like SwiftKey or gboard. I got the apks from apkmirror how does updating them work?
