### ISSUE TITLE
[Sugesstion] Add Support for groq.com API

### ISSUE THREAD

**Issue by RizkyM2999** [Mino260806/KeyboardGPT#2]
https://groq.com/
Groq have free API and use Llama Model

**Comment by Mino260806** [comment]
Excellent suggestion! Actually you can already use it by changing base url in chatgpt (but there's a bug that I'm still fixing), but I'd rather create a new entry for it to keep things tidied

**Comment by Mino260806** [comment]
Added in commit 5776e40f9c26f52c7672f752308c03f3695c27b9, update to latest version and enjoy !
