### ISSUE TITLE
Arabic text input display for prompt 

### ISSUE THREAD

**Issue by bigjackwww** [Mino260806/KeyboardGPT#4]
I am experiencing an issue with the Arabic text input in the KeyboardGPT app. Arabic script should be displayed from right to left, but currently, it appears to be aligned from left to right, which is not consistent with standard Arabic text formatting. Btw i can't generate something in arabic words...

**Comment by Mino260806** [comment]
What do you mean by "KeyboardGPT app" ? If you mean the dialog, it's aligned normally for me. If you mean the keyboard, it depends on which one you use, for example in Gboard arabic is displayed fine. Maybe you can send a screenshot to better explain the problem ?

**Comment by bigjackwww** [comment]
I mean i can't generate when i start texting with arabic language 

https://github.com/user-attachments/assets/9a1a3253-e7ac-4ba9-86f3-c04fc20b708e

**Comment by Mino260806** [comment]
It's not the same "?" character, long press it and choose the latin one

?https://github.com/user-attachments/assets/b5ea11ff-7bf7-43c6-a6d1-b37398e07b1b

**Comment by bigjackwww** [comment]
Ok thank you very much
