### ISSUE TITLE
Samsung Keyboard is not appearing in LSPatch when searching

### ISSUE THREAD

**Issue by jimmietron** [Mino260806/KeyboardGPT#5]
Hello,

Hopefully someone can help with this. On my non-rooted Galaxy S24+, when I try to patch Samsung Keyboard in LSPatch it does not appear when I search for it. I also have Swiftkey installed and that one does appear when searching for installed apps, but Samsung Keyboard, which is my default, does not. Any help would be greatly appreciated.

**Comment by Mino260806** [comment]
So Samsung Keyboard is a system app. Unfortunately you can't patch a system app unless you have root. There's nothing we can do about it
